In [8]:
import numpy as np

### Задание 1

In [9]:
a = np.transpose(([1, 2, 3, 3, 1], [6, 8, 11, 10, 7]))

In [10]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [13]:
a_centered = a - mean_a

In [14]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [15]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [16]:
a_cov = a_centered_sp/(a.shape[0] - 1)

In [17]:
a_cov

2.0

### Задание 4

In [18]:
a_cov1 = np.cov(a.T)
a_cov1

array([[1. , 2. ],
       [2. , 4.3]])